[2025-05-19T02:10:39.106+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dados.upload_raw_data_to_bronze manual__2025-05-19T02:05:16.911273+00:00 [queued]>
[2025-05-19T02:10:39.119+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dados.upload_raw_data_to_bronze manual__2025-05-19T02:05:16.911273+00:00 [queued]>
[2025-05-19T02:10:39.120+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-19T02:10:39.290+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_raw_data_to_bronze> on 2025-05-19 02:05:16.911273+00:00
[2025-05-19T02:10:39.298+0000] {standard_task_runner.py:57} INFO - Started process 67 to run task
[2025-05-19T02:10:39.304+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dados', 'upload_raw_data_to_bronze', 'manual__2025-05-19T02:05:16.911273+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_dados.py', '--cfg-path', '/tmp/tmp566d_72_']
[2025-05-19T02:10:39.307+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask upload_raw_data_to_bronze
[2025-05-19T02:10:39.497+0000] {task_command.py:415} INFO - Running <TaskInstance: pipeline_dados.upload_raw_data_to_bronze manual__2025-05-19T02:05:16.911273+00:00 [running]> on host c48fc2b8b1a5
[2025-05-19T02:10:40.616+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dados' AIRFLOW_CTX_TASK_ID='upload_raw_data_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T02:05:16.911273+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T02:05:16.911273+00:00'
[2025-05-19T02:10:40.999+0000] {logging_mixin.py:151} INFO - Erro ao carregar os dados brutos: [Errno 13] Permission denied: '/opt/airflow/data/bronze/dados_bronze.csv'
[2025-05-19T02:10:41.000+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_pipeline_dados.py", line 40, in upload_raw_data_to_bronze
    df.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/bronze/dados_bronze.csv'
[2025-05-19T02:10:41.020+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pipeline_dados, task_id=upload_raw_data_to_bronze, execution_date=20250519T020516, start_date=20250519T021039, end_date=20250519T021041
[2025-05-19T02:10:41.133+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task upload_raw_data_to_bronze ([Errno 13] Permission denied: '/opt/airflow/data/bronze/dados_bronze.csv'; 67)
[2025-05-19T02:10:41.211+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-19T02:10:41.288+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
